// clang-format off
// NOLINTBEGIN
// GENERATED BY NNCBINDGEN from nn_TimeSpan.h
#pragma once

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef int64_t nnTimeSpan;

#ifdef __cplusplus
}
#endif

// NOLINTEND
// clang-format off
