// clang-format off
// NOLINTBEGIN
// GENERATED BY NNCBINDGEN from ssl.h
#pragma once

#include <stdint.h>
#include <stdbool.h>

#include <nnc/nn_Result.h>
#include <nnc/ssl/ssl_Connection.h>
#include <nnc/ssl/ssl_Context.h>

#ifdef __cplusplus
extern "C" {
#endif

nnResult nnsslInitialize();
nnResult nnsslInitializeWithConcurrencyLimit(uint32_t concurrencyLimit);
nnResult nnsslFinalize();

#ifdef __cplusplus
}
#endif

// NOLINTEND
// clang-format off
